### PR TITLE
use CONF_CFLAGS to pass extra CFLAGS

### PR DESCRIPTION
**Pull request by yuyang0**
sometimes specifying extra CFLAGS is needed in command line, CONF_CFLAGS seems a good choices.

### CODE REVIEW

**Comment by whl739** [comment]
But why not `EXTRA_CFLAGS`?

**Comment by yuyang0** [comment]
because if use `EXTRA_CFLAGS`, `NORMAL_C` and `NORMAL_S` also need change, I think `CONF_CFLAGS` is not a good name too, but I want to make this PR as samll as possible

**Comment by yuyang0** [comment]
I closed this PR, but a way to pass extra cflags is really needed, you can  choose a proper way to provide this feature.

**Comment by amjy** [comment]
It means lvs toa option can enable like this ?
`export CONF_CFLAGS="-DLVS_TCPOPT_TOA"; make`

**Comment by yuyang0** [comment]
yes, just use `make  CONF_CFLAGS="-DLVS_TCPOPT_TOA"`

**Pull request merged**
