### PR TITLE
Nginx: bugfix, secondary worker should be spawned after primary completing initialization of fstack(dpdk)

### PR DESCRIPTION
**Pull request by firesidefox**
Secondary workers may be spawned before primary worker completing initialization of fstack(dpdk), so errors occurred, for one, in kni.

### CODE REVIEW

**Comment by whl739** [comment]
There's a problem here.
If the f-stack primary process hasn't been initialized successful(for example, the nic hasn't been offloaded, or the hugepage hasn't been configured, etc..), the nginx master will cause an error: `sem_timedwait timeout`.

Any opnion about this?

**Comment by firesidefox** [comment]
Do you mean that we should give a more friendly hint?  And the nginx master should exit silently?

**Comment by whl739** [comment]
Yes, we should let user know the primary fails in any way , for example log it.

**Comment by firesidefox** [comment]
Got it. I'll fix it!

**Comment by firesidefox** [comment]
@whl739 
When an error occurs during the initialization, dpdk does log and exit/abort. And ff ( short for f-stack glue layer)  does likewise. So we get a question : how does ff log?
ff uses ```printf``` for now. But this is not always effective, as nginx_fstack.
I think we have two solutions:
1. Log with ```ret_exit```/```ret_pain```, and add configuration option to let the user enable dpdk's syslog. Before ret_eal_init, we cannot log, but we can return an errorcode.
2. Implement a log module for ff, and allow user to customize the output.

I prefer the 1nd.  What do you think?

**Comment by whl739** [comment]
> If the f-stack primary process hasn't been initialized successful(for example, the nic hasn't been offloaded, or the hugepage hasn't been configured, etc..), the nginx master will cause an error: sem_timedwait timeout.

>Yes, we should let user know the primary fails in any way , for example log it.

What do i mean is that when primary fails to initialize, the master shouldn't wait for timeout, it should exit immediately, and log an error: "the primary failed to initialize" but not a timeout error.
If "don't wait" is difficult to implement, we can just modify the log message from
```
if (r == -1) {
    ngx_log_error(NGX_LOG_ERR, cycle->log, ngx_errno,
            "start worker processes sem_timedwait");
    exit(2);
}
```
to
```
if (r == -1) {
    ngx_log_error(NGX_LOG_ERR, cycle->log, ngx_errno,
        "primary worker process failed to initialize");
    exit(2);
}
```

> 1.Log with ret_exit/ret_pain, and add configuration option to let the user enable dpdk's syslog. Before ret_eal_init, we cannot log, but we can return an errorcode.
2.Implement a log module for ff, and allow user to customize the output.

And for the above, this may be more effective, but there's more work, no need to do this.

**Pull request merged**
