### PR TITLE
Merge syscall replace

### PR DESCRIPTION
**Pull request by amjy**
- [x] Replace syscalls in ff_init.c; 
- [x] Reserve some fd for system by freebsd.fdstart in config.ini.
- [x] Epoll optimization.
- [x] Nginx tested ok.

- [x] If a 'fd' in syscall's arguments, it can be called by both f-stack and normal, such as write/read/send/select/eopll_ctl and so on.
- function socket() for f-stack and socket_raw() for normal.
- function fepoll_create() for f-stack and epoll_create() for normal, not epoll_create_raw because conflicted with dpdk.
- function read(), epoll_ctl(), select() and so on both f-stack and normal.
- function open() for normal only.
 
- [x] App call ff_init() at app init, and change process to ff_run(). Reference: helloworld examples/main.c and main_epoll.c; make/make epoll/make normal

- [x] **redis in f-stack master build failed at jemalloc.** I tested these features in a official version pushed to uvuv/redis-fstack.
- [ ] **micro thread is not supported now !!! help me! help me! help me!!!!**

### CODE REVIEW

**Comment by amjy** [comment]
I have found the problem of redis jemalloc build error !!
following files ignored by .gitignore when you commit it.
deps/jemalloc/VERSION
deps/jemalloc/configure
deps/jemalloc/doc/jemalloc.3
deps/jemalloc/doc/jemalloc.html

**Comment by whl739** [comment]
Thanks for your pull request.
Minor comments below.
1. It's best to send a smaller patch at a time. 
2. I think it's better to add these hook functions on a single file, for example ff_hook.
3. I still want user to decide whether or not to have these hook functions.

**Comment by amjy** [comment]
@whl739 
OK！ comment 2 and 3 I will do it.
But what do you mean the smaller patch, upload a total modified diff or merge all commits in one?

**Comment by whl739** [comment]
I mean merge all commits in one.

**Comment by amjy** [comment]
@whl739  move to #34 
I have done as you said, but I don't think only one commit is a good idea. ^_^

**Pull request closed without merging**
