### PR TITLE
Only 7 LSBs of the rss hash result should be used when calculate queue index.

### PR DESCRIPTION
**Pull request by ppliu1979**
Only 7 LSBs of the rss hash result should be used when calculate queue index in ff_dpdk_if.c

### CODE REVIEW

**Review by whl739 — COMMENTED** [review]
Could you explain that why it should be? Thank you.

**Comment by ppliu1979** [comment]
please refer  to this page, [http://blog.csdn.net/bestboyxie/article/details/64469679](http://blog.csdn.net/bestboyxie/article/details/64469679)
and  [http://www.cnblogs.com/danxi/p/6761997.html](url)
after got the 32bit hash result, only last 7 bits will be used to map to the redirection table.

**Comment by ppliu1979** [comment]
and please refer to the Intel 82599 10 GbE Controller Datasheet, there is following sentences:
7.1.2.8.2 Redirection Table
The redirection table is a 128-entry structure, indexed by the seven LSBs of the hash
function output.

**Comment by ppliu1979** [comment]
I use nginx on f-stack as a reverse proxy, and when I started two more nginx processes, sometime the upstream connection will timeout. Debug process show that the queue id ff_rss_check function predicted is differ from the hardware rss unit's result. So the return package went to the different queue from the sent out queue. By using 7 bits mask, this problem never occur.

**Comment by whl739** [comment]
Thanks for your feedback, this is very helpful for me.
I'll do a test, after that i will merge this pull request.

**Comment by ppliu1979** [comment]
Please note that different netcard's redirection table may have different entry size, Intel 82599 and X520 has 128 entries, so the mask is 7 bits, and some netcards has 64 entries, should use 6bits mask. The reta_size in struct rte_eth_dev_info contains this info. So you need to find out the real reta size of your netcard. (reta = redirection table).  If you can find a way to pass this reta_size into ff_rss_check funtion ,it will solve this problem perfectly.

**Comment by whl739** [comment]
We can define `reta_size` as a global variable and  set its value from `dev_info` when `init_port_start()` .

**Comment by ppliu1979** [comment]
Yes, it's easy, but what if there are two more netcards with different reta_sizes? And will ff_rss_check known which one it is using at that time?

**Comment by whl739** [comment]
This is the point. I must figure out a way to know which port is using at that time.

**Comment by whl739** [comment]
Could you please push a new pr for compliing error in ngx_ff_channel.c or i just fix it?

**Comment by ppliu1979** [comment]
ok , I will do a new one

**Comment by ppliu1979** [comment]
You can close this one. I will wait for your final solution. Thank you very much.

**Pull request closed without merging**
